# Generated by Django 6.0.6 on 2026-06-08 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='status',
            new_name='ativa',
        ),
    ]
