# Generated by Django 6.0.6 on 2026-06-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0005_alter_noticia_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='data_publicao',
            new_name='data_publicacao',
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='noticias/'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='legenda',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
